#!/usr/bin/env bash

# bash < <( curl https://github.com/pierot/server-installer/raw/master/bash-linode/install )

# REQUIRE ROOT USER
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Not running as root"
    exit
fi

# DOWNLOAD SCRIPTS
wget https://github.com/pierot/server-installer/raw/master/bash-linode/install_1 --no-check-certificate
wget https://github.com/pierot/server-installer/raw/master/bash-linode/install_2 --no-check-certificate
wget https://github.com/pierot/server-installer/raw/master/bash-linode/install_3 --no-check-certificate
wget https://github.com/pierot/server-installer/raw/master/bash-linode/install_4 --no-check-certificate

# MAKE EXEC
chmod +x install*

# EXECUTE
sudo ./install_1
sudo ./install_2
./install_3
sudo ./install_4

# REMOVE ALL
rm install*