#!/usr/bin/env bash

#sudo su # ROOT USER

# RVM (RUBY)
bash < <( curl -L http://bit.ly/rvm-install-system-wide )

#echo '# RVM \n' >> ~/.bashrc
#echo '[[ -s "/usr/local/rvm/scripts/rvm" ]] && source "/usr/local/rvm/scripts/rvm"' >> ~/.bashrc

#echo '# RVM \n' >> /etc/skel/.bashrc
#echo '[[ -s "/usr/local/rvm/scripts/rvm" ]] && source "/usr/local/rvm/scripts/rvm"' >> /etc/skel/.bashrc

echo '# Load RVM if it is installed,' >> ~/.bashrc
echo '#  first try to load  user install' >> ~/.bashrc
echo '#  then try to load root install, if user install is not there.' >> ~/.bashrc
echo 'if [ -s "$HOME/.rvm/scripts/rvm" ] ; then' >> ~/.bashrc
echo '  . "$HOME/.rvm/scripts/rvm"' >> ~/.bashrc
echo 'elif [ -s "/usr/local/rvm/scripts/rvm" ] ; then' >> ~/.bashrc
echo '  . "/usr/local/rvm/scripts/rvm"' >> ~/.bashrc
echo 'fi' >> ~/.bashrc

echo '# Load RVM if it is installed,' >> /etc/skel/.bashrc
echo '#  first try to load  user install' >> /etc/skel/.bashrc
echo '#  then try to load root install, if user install is not there.' >> /etc/skel/.bashrc
echo 'if [ -s "$HOME/.rvm/scripts/rvm" ] ; then' >> /etc/skel/.bashrc
echo '  . "$HOME/.rvm/scripts/rvm"' >> /etc/skel/.bashrc
echo 'elif [ -s "/usr/local/rvm/scripts/rvm" ] ; then' >> /etc/skel/.bashrc
echo '  . "/usr/local/rvm/scripts/rvm"' >> /etc/skel/.bashrc
echo 'fi' >> /etc/skel/.bashrc

# Add current user to rvm group
usermod -aG rvm `/usr/bin/whoami`

#exit # EXIT SUDO SU

source ~/.bashrc